import { describe, it, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
process.env.NODE_ENV='test';process.env.METADATA_LAB_TMP=path.join(os.tmpdir(),'metadata-lab-test-'+Date.now());
const mod=await import('../server/exiftool.js');const {createServer}=await import('../server/httpApp.js');let server,base;
before(async()=>{server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`});after(async()=>{server.close();await fs.rm(process.env.METADATA_LAB_TMP,{recursive:true,force:true})});beforeEach(async()=>{await fs.rm(process.env.METADATA_LAB_TMP,{recursive:true,force:true});await fs.mkdir(process.env.METADATA_LAB_TMP,{recursive:true})});
describe('ExifTool safety helpers',()=>{it('generates allowed command arguments without shell string',()=>{const built=mod.buildExifArgs({preset:'maximum',flags:['-warning'],inputPath:'/tmp/in.jpg'});assert.deepEqual(built.args,['-a','-U','-G1','-s','-warning','/tmp/in.jpg'])});it('rejects disallowed arguments',()=>assert.throws(()=>mod.buildExifArgs({preset:'basic',flags:['-execute'],inputPath:'/tmp/in.jpg'}),/not allowed/));it('prevents path traversal',()=>assert.throws(()=>mod.resolveTemp('..','etc','passwd'),/Invalid temporary path/));it('requires output for writes and never overwrites original',()=>{assert.throws(()=>mod.buildExifArgs({preset:'privacy',inputPath:'/tmp/in.jpg'}),/Output path/);const b=mod.buildExifArgs({preset:'privacy',inputPath:'/tmp/in.jpg',outputPath:'/tmp/out.jpg'});assert.ok(b.args.includes('-o'));assert.notEqual(b.args[b.args.indexOf('-o')+1],'/tmp/in.jpg')})});
describe('uploads and deletion',()=>{it('accepts permitted uploads',async()=>{const fd=new FormData();fd.append('file',new Blob(['hello'],{type:'text/plain'}),'a.txt');const r=await fetch(base+'/api/upload',{method:'POST',body:fd});const j=await r.json();assert.equal(r.status,200);assert.equal(j.filename,'a.txt');assert.ok(j.fileId)});it('rejects unsupported uploads',async()=>{const fd=new FormData();fd.append('file',new Blob(['x'],{type:'application/octet-stream'}),'a.bin');const r=await fetch(base+'/api/upload',{method:'POST',body:fd});assert.ok(r.status>=400)});it('panic deletes temporary uploads',async()=>{await fs.writeFile(mod.resolveTemp('marker'),'x');const r=await fetch(base+'/api/panic',{method:'POST'});assert.equal(r.status,200);await assert.rejects(fs.stat(mod.resolveTemp('marker')))})});

describe('command API and reliability',()=>{it('generates commands through the API',async()=>{const fd=new FormData();fd.append('file',new Blob(['hello'],{type:'text/plain'}),'cmd.txt');const up=await (await fetch(base+'/api/upload',{method:'POST',body:fd})).json();const r=await fetch(base+'/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...up,preset:'basic',flags:['-warning'],edits:{}})});const j=await r.json();assert.equal(r.status,200);assert.match(j.command,/exiftool/);assert.ok(j.args.includes('-warning'))});it('returns 404 for missing downloads',async()=>{const r=await fetch(base+'/api/download/missing/nope.jpg');const j=await r.json();assert.equal(r.status,404);assert.match(j.error,/not found|expired/i)});it('rejects malformed multipart cleanly without paths',async()=>{const r=await fetch(base+'/api/upload',{method:'POST',headers:{'content-type':'multipart/form-data; boundary=x'},body:'not multipart'});const j=await r.json();assert.equal(r.status,400);assert.match(j.error,/Multipart upload/);assert.doesNotMatch(j.error,new RegExp(process.env.METADATA_LAB_TMP.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});it('rejects invalid temporary paths in command requests',async()=>{const r=await fetch(base+'/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileId:'..',storedName:'passwd',preset:'basic'})});const j=await r.json();assert.equal(r.status,400);assert.match(j.error,/not found|expired|Invalid temporary path/);assert.doesNotMatch(j.error,new RegExp(process.env.METADATA_LAB_TMP.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});it('builds write commands with output copy arguments before the original',()=>{const b=mod.buildExifArgs({preset:'privacy',inputPath:'/tmp/original.jpg',outputPath:'/tmp/copy.jpg'});assert.equal(b.modifies,true);assert.equal(b.args.at(-1),'/tmp/original.jpg');assert.deepEqual(b.args.slice(b.args.indexOf('-o'),b.args.indexOf('-o')+2),['-o','/tmp/copy.jpg'])})});

describe('frontend workflow markup',()=>{it('separates generate, copy, and run controls with disabled copy state',async()=>{const html=await fs.readFile(path.resolve('public/index.html'),'utf8');assert.match(html,/Generate Command/);assert.match(html,/Copy Command/);assert.match(html,/Run ExifTool/);assert.match(html,/id="clip" type="button" disabled/);assert.match(html,/id="toolCopy" type="button" disabled/)});it('contains panic confirmation dialog and clipboard fallback implementation',async()=>{const html=await fs.readFile(path.resolve('public/index.html'),'utf8');const js=await fs.readFile(path.resolve('public/app.js'),'utf8');assert.match(html,/Confirm Panic Delete/);assert.match(html,/temporary uploads, generated output files, and this browser's session history/);assert.match(js,/execCommand\('copy'\)/);assert.match(js,/Panic Delete succeeded/);assert.match(js,/Panic Delete failed/)});it('contains XP menu items',async()=>{const html=await fs.readFile(path.resolve('public/index.html'),'utf8');for(const label of ['Open File','Clear Current File','Panic Delete','File Selection','Quick Presets','Metadata Editing','Advanced Flags','Command Preview','Results','Session History','Generate Command','Run ExifTool','Reset Options','Enable Expert Mode','About Metadata Lab','ExifTool Flag Guide'])assert.match(html,new RegExp(label));})});
