import http from 'node:http';
import fs from 'node:fs/promises';
import fss from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const memorySessions = new Map();
const memoryVaultRoot = path.resolve(process.env.MEMORY_VAULT_ROOT || '.memory-vaults');
const DEMO_VAULT = {
  version: 1, createdAt: '2026-07-15T00:00:00.000Z', fictional: true,
  settings: { telemetry: false, externalProviders: false, autoLockMinutes: 15 },
  artifacts: [
    { id: 'art-note-2019-walks', type: 'note', title: 'Long walks and the atlas idea', source: 'demo journal', date: { kind: 'date', value: '2019-06-18', provenance: 'direct_source_metadata' }, text: 'After long walks near Lake Michigan I keep sketching the Atlas project. Maya says the city makes me braver.', people: ['Maya'], places: ['Chicago'], projects: ['Atlas'], themes: ['walking','reinvention','writing'], emotions: [{label:'creative', provenance:'explicit'}, {label:'hopeful', provenance:'language_inference'}], confidence: .86 },
    { id: 'art-email-2020-daniel', type: 'email', title: 'Daniel: checking in', source: 'demo mbox', date: { kind: 'exact', value: '2020-11-04T16:20:00-05:00', provenance: 'direct_source_metadata' }, text: 'Daniel wrote during the move: if the studio gets too quiet, call me. I replied about feeling overwhelmed but determined.', people: ['Daniel'], places: ['Boston'], projects: ['Studio move'], themes: ['transition','friendship'], emotions: [{label:'overwhelmed', provenance:'explicit'}, {label:'connected', provenance:'language_inference'}], confidence: .82 },
    { id: 'art-ics-2021-woodshop', type: 'calendar', title: 'Woodshop orientation', source: 'demo calendar.ics', date: { kind: 'exact', value: '2021-03-14T18:00:00-04:00', provenance: 'direct_source_metadata' }, text: 'Calendar event at North End Community Workshop. Project: folding writing desk.', people: [], places: ['Boston'], projects: ['Woodworking'], themes: ['making','routine'], emotions: [{label:'ambitious', provenance:'language_inference'}], confidence: .74 },
    { id: 'art-spotify-2022-train', type: 'listening_history', title: 'Night train playlist cluster', source: 'demo Spotify JSON', date: { kind: 'range', start: '2022-09-02', end: '2022-10-12', provenance: 'deterministic_extraction' }, text: 'Repeated plays: Night Train Sketches, A New Room, Harbor Static during apartment search and train trips.', people: [], places: ['New York','Philadelphia'], projects: ['New Room'], themes: ['music','transition','travel'], emotions: [{label:'searching', provenance:'media_suggestion'}], confidence: .69 },
    { id: 'art-photo-2023-chicago', type: 'image', title: 'Chicago studio window', source: 'demo photo metadata', date: { kind: 'conflict', candidates: ['2023-05-02T10:14:00-05:00','2023-05-03T03:14:00Z'], provenance: 'direct_source_metadata' }, text: 'Photo metadata places the studio window near Chicago. Caption says: first morning back, starting over.', people: ['Maya'], places: ['Chicago'], projects: ['Atlas'], themes: ['reinvention','studio'], emotions: [{label:'renewed', provenance:'caption_inference'}], confidence: .77, location: { lat: 41.8781, lon: -87.6298, confidence: .72, provenance: 'direct_source_metadata' } },
    { id: 'art-voice-2024-dream', type: 'voice_transcript', title: 'Recurring boat dream', source: 'demo transcript', date: { kind: 'approximate', value: '2024-01', provenance: 'user_entered' }, text: 'Voice memo transcript: the boat library dream again. Maybe the old goal is a mobile archive, not just an app.', people: [], places: [], projects: ['Boat library','Atlas'], themes: ['recurring aspiration','archive'], emotions: [{label:'reflective', provenance:'language_inference'}, {label:'uncertain', provenance:'explicit'}], confidence: .64 }
  ],
  people: [{id:'Maya', label:'Maya'}, {id:'Daniel', label:'Daniel'}],
  places: [{id:'Chicago', label:'Chicago', lat:41.8781, lon:-87.6298}, {id:'Boston', label:'Boston', lat:42.3601, lon:-71.0589}, {id:'New York', label:'New York', lat:40.7128, lon:-74.006}, {id:'Philadelphia', label:'Philadelphia', lat:39.9526, lon:-75.1652}],
  corrections: [], importSessions: []
};
function vaultPath(name='default') { return path.join(memoryVaultRoot, path.basename(name), 'vault.mc'); }
export function deriveMemoryKey(passphrase, salt) { return crypto.scryptSync(passphrase, salt, 32, { N: 1<<14, r: 8, p: 1, maxmem: 64 * 1024 * 1024 }); }
export function encryptMemoryVault(data, passphrase) { const salt=crypto.randomBytes(16), iv=crypto.randomBytes(12), key=deriveMemoryKey(passphrase, salt); const cipher=crypto.createCipheriv('aes-256-gcm', key, iv); const ciphertext=Buffer.concat([cipher.update(JSON.stringify(data),'utf8'), cipher.final()]); return { kdf:'scrypt', cipher:'AES-256-GCM', salt:salt.toString('base64'), iv:iv.toString('base64'), tag:cipher.getAuthTag().toString('base64'), ciphertext:ciphertext.toString('base64') }; }
export function decryptMemoryVault(blob, passphrase) { const key=deriveMemoryKey(passphrase, Buffer.from(blob.salt,'base64')); const decipher=crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(blob.iv,'base64')); decipher.setAuthTag(Buffer.from(blob.tag,'base64')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(blob.ciphertext,'base64')), decipher.final()]).toString('utf8')); }
function tokenVector(text='') { const counts={}; for (const w of text.toLowerCase().match(/[a-z][a-z0-9-]{2,}/g)||[]) counts[w]=(counts[w]||0)+1; return counts; }
function checksum(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }
function inferArtifact(file) { const name=file.filename||'memory'; const text=file.content.toString('utf8').slice(0,200000); const ext=path.extname(name).toLowerCase(); const type= ext==='.ics'?'calendar':ext==='.eml'||ext==='.mbox'?'email':ext==='.csv'?'location_history':ext==='.json'?'json':ext==='.md'||ext==='.txt'?'note':ext==='.pdf'?'pdf':/jpe?g|png|webp|heic/.test(ext)?'image':/mp3|m4a|wav/.test(ext)?'audio':'document'; const words=text.match(/[A-Z][a-z]+/g)||[]; const people=[...new Set(words.filter(w=>!['The','This','After','Maybe','Project'].includes(w)).slice(0,4))]; const themes=['creative','travel','project','music','walk','writing','move','family','transition'].filter(t=>text.toLowerCase().includes(t)); const emotions=['creative','restless','hopeful','reflective','grieving','connected','isolated','ambitious','peaceful','overwhelmed','playful','searching','renewed','uncertain'].filter(e=>text.toLowerCase().includes(e)).map(label=>({label, provenance:'explicit'})); return { id:'art-'+crypto.randomUUID(), type, title:name, source:'manual import', checksum:checksum(file.content), date:{kind:'unknown', provenance:'deterministic_extraction'}, text, people, places:[], projects:themes.includes('project')?['Imported project']:[], themes, emotions, confidence:.55, embedding:tokenVector(text), provenance:{importer:'generic-file-adapter', preservedOriginal:'encrypted vault payload'} }; }
function buildInsights(vault) { const arts=vault.artifacts||[]; const byProject={}; for(const a of arts) for(const p of a.projects||[]) (byProject[p] ||= []).push(a); const insights=[]; for(const [p,rows] of Object.entries(byProject)) if(rows.length>1) insights.push({id:'ins-'+p, category:'Recurring aspirations', observation:p+' resurfaces across '+rows.length+' artifacts.', evidence:rows.map(r=>r.id), confidence: Math.min(.9,.45+rows.length*.12), method:'deterministic co-occurrence over project labels', reasoning:'The same project label appears in multiple dated artifacts.', alternative:'The label may be broad or reused for different ideas.'}); const travel=arts.filter(a=>(a.themes||[]).includes('travel')); if(travel.length) insights.push({id:'ins-travel-reflection', category:'Movement and travel', observation:'Reflective material appears near travel records.', evidence:travel.map(a=>a.id), confidence:.58, method:'theme co-occurrence', reasoning:'Artifacts tagged travel also contain reflective or transition language.', alternative:'This may reflect import bias in the demo or selected files.'}); return insights; }
function answerQuestion(vault, q) { const terms=(q.toLowerCase().match(/[a-z]{3,}/g)||[]).filter(w=>!['what','when','show','with','were','have','does','life','where'].includes(w)); const scored=(vault.artifacts||[]).map(a=>({a, score:terms.reduce((n,t)=>n+(JSON.stringify(a).toLowerCase().includes(t)?1:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,5); return { interpretedQuestion:q, queryPlan:{fullTextTerms:terms, structuredFilters:[], vectorSimilarity:'token-overlap fallback', graphTraversal:'people/place/project co-occurrence'}, answer: scored.length?'I found '+scored.length+' supporting artifact(s). This is evidence for exploration, not a definitive psychological conclusion.':'I do not have enough evidence.', artifacts:scored.map(x=>x.a.id), confidence: scored.length?Math.min(.82,.35+scored.length*.1):.12, unsupportedGaps: scored.length?['Dates, locations, and feelings may be incomplete or user-corrected later.']:['No matching local artifacts were found.'] }; }
async function memoryApi(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/memory/demo') return json(res,200,{vault:{...DEMO_VAULT, insights:buildInsights(DEMO_VAULT)}});
 if(req.method==='GET'&&url.pathname==='/api/memory/status') return json(res,200,{vaultRoot:memoryVaultRoot, telemetry:false, localOnly:true, encryption:'AES-256-GCM at rest; scrypt KDF MVP'});
 if(req.method==='POST'&&url.pathname==='/api/memory/create'){ const p=JSON.parse((await body(req)).toString()||'{}'); const v={...DEMO_VAULT, artifacts:[], fictional:false, createdAt:new Date().toISOString()}; await fs.mkdir(path.dirname(vaultPath(p.name)),{recursive:true,mode:0o700}); await fs.writeFile(vaultPath(p.name), JSON.stringify(encryptMemoryVault(v,p.passphrase||'')), {mode:0o600}); return json(res,200,{ok:true,path:vaultPath(p.name)}); }
 if(req.method==='POST'&&url.pathname==='/api/memory/open'){ const p=JSON.parse((await body(req)).toString()||'{}'); const blob=JSON.parse(await fs.readFile(vaultPath(p.name),'utf8')); const vault=decryptMemoryVault(blob,p.passphrase||''); const token=crypto.randomUUID(); memorySessions.set(token,{name:path.basename(p.name||'default'), passphrase:p.passphrase, vault, last:Date.now()}); return json(res,200,{token,vault:{...vault, insights:buildInsights(vault)}}); }
 if(req.method==='POST'&&url.pathname==='/api/memory/import'){ const token=url.searchParams.get('token'); const s=memorySessions.get(token); if(!s) return json(res,401,{error:'Vault is locked or session expired.'}); const f=await parseMultipart(req); const a=inferArtifact(f); if(!s.vault.artifacts.some(x=>x.checksum===a.checksum)) s.vault.artifacts.push(a); s.vault.importSessions.push({id:'imp-'+crypto.randomUUID(), at:new Date().toISOString(), filename:f.filename, checksum:a.checksum}); await fs.writeFile(vaultPath(s.name), JSON.stringify(encryptMemoryVault(s.vault,s.passphrase)), {mode:0o600}); return json(res,200,{artifact:a,vault:{...s.vault, insights:buildInsights(s.vault)}}); }
 if(req.method==='POST'&&url.pathname==='/api/memory/query'){ const p=JSON.parse((await body(req)).toString()||'{}'); const vault=p.vault || memorySessions.get(p.token)?.vault || DEMO_VAULT; return json(res,200,answerQuestion(vault,p.question||'')); }
 if(req.method==='POST'&&url.pathname==='/api/memory/export'){ const p=JSON.parse((await body(req)).toString()||'{}'); const vault=p.vault || memorySessions.get(p.token)?.vault || DEMO_VAULT; return json(res,200,{exportedAt:new Date().toISOString(), vault:{...vault, insights:buildInsights(vault)}}); }
 return false;
}

import { config } from './config.js';
import { buildExifArgs, buildExplorerArgs, ensureTempRoot, isAllowedMime, parseExplorerJson, randomId, resolveTemp, runExiftool, safeBasename, presets } from './exiftool.js';
import { assertTimestampWithinDuration, buildCommand, buildInvestigationReport, capabilitiesForFile, detectMagic, embeddedOutputPath, extractPrintableStrings, frameOutputPath, getToolAvailability, hashFile, outputLimits, parseBinwalk, parseFfprobeJson, parseIdentify, parseMediaInfoJson, parseQrOutput, reportText, safeRunTool, stringLengthAllowlist, toolRegistry, validateOcrLanguage, validateTimestamp, verifyHash } from './tools.js';

const rates = new Map();
function json(res, code, obj) { res.writeHead(code, { 'content-type': 'application/json' }); res.end(JSON.stringify(obj)); }
function publicError(e) { return /ENOENT/.test(e.message) ? 'ExifTool is not installed or not available.' : e.message.replaceAll(config.tempRoot, '[temporary directory]'); }
async function body(req) { const a = []; let size = 0; for await (const c of req) { a.push(c); size += c.length; if (size > config.maxUploadBytes + 1e6) throw Error('Upload too large.'); } return Buffer.concat(a); }
async function parseMultipart(req) {
  const ct = req.headers['content-type'] || '';
  const m = ct.match(/boundary=(?:(?:"([^"]+)")|([^;]+))/i);
  if (!m) throw Error('Multipart form data is required.');
  const boundary = Buffer.from('--' + (m[1] || m[2]).trim());
  const data = await body(req);
  const startBoundary = data.indexOf(boundary);
  if (startBoundary < 0) throw Error('Multipart upload could not be parsed.');
  const start = startBoundary + boundary.length + 2;
  const end = data.indexOf(Buffer.concat([Buffer.from('\r\n'), boundary]), start);
  if (end < 0) throw Error('Multipart upload could not be parsed.');
  const part = data.subarray(start, end);
  const headEnd = part.indexOf('\r\n\r\n');
  if (headEnd < 0) throw Error('Multipart upload could not be parsed.');
  const head = part.subarray(0, headEnd).toString();
  const content = part.subarray(headEnd + 4);
  const filename = (head.match(/filename="([^"]*)"/) || [])[1] || 'upload';
  const type = (head.match(/Content-Type: ([^\r\n]+)/i) || [])[1] || 'application/octet-stream';
  return { filename, type, content };
}
function rate(req, res) { const ip = req.socket.remoteAddress, now = Date.now(), r = rates.get(ip) || { n: 0, t: now }; if (now - r.t > config.rateLimitWindowMs) { r.n = 0; r.t = now; } r.n++; rates.set(ip, r); if (r.n > config.rateLimitMax) { json(res, 429, { error: 'Too many requests.' }); return true; } }
async function handler(req, res) {
  try {
    if (rate(req, res)) return;
    await ensureTempRoot();
    const url = new URL(req.url, 'http://x');
    if (url.pathname.startsWith('/api/memory/')) { const handled = await memoryApi(req, res, url); if (handled !== false) return; }
    if (req.method === 'GET' && url.pathname === '/api/config') return json(res, 200, { maxUploadBytes: config.maxUploadBytes, presets, stringLengthAllowlist });
    if (req.method === 'GET' && url.pathname === '/api/tools') return json(res, 200, { tools: await getToolAvailability(url.searchParams.get('refresh') === '1'), aptCommand: 'sudo apt install -y libimage-exiftool-perl mediainfo ffmpeg imagemagick binutils zbar-tools tesseract-ocr binwalk file' });
    if (req.method === 'GET' && url.pathname === '/api/about') { let exiftoolVersion = 'Unavailable'; try { const v = await runExiftool(['-ver'], 5000); if (v.code === 0) exiftoolVersion = v.stdout.trim() || 'Unavailable'; } catch {} return json(res, 200, { name: 'Metadata Lab', version: '1.0.0', exiftoolVersion }); }
    if (req.method === 'POST' && url.pathname === '/api/upload') { const f = await parseMultipart(req); if (!isAllowedMime(f.type)) return json(res, 400, { error: 'Unsupported file type.' }); if (!f.content.length) return json(res, 400, { error: 'Uploaded file is empty.' }); if (f.content.length > config.maxUploadBytes) return json(res, 413, { error: 'Upload exceeds configured size limit.' }); const fileId = randomId(), storedName = `${randomId()}-${safeBasename(f.filename)}`, dir = resolveTemp(fileId); await fs.mkdir(dir, { recursive: true, mode: 0o700 }); await fs.writeFile(resolveTemp(fileId, storedName), f.content, { mode: 0o600 }); const magic = await detectMagic(resolveTemp(fileId, storedName), f.type); return json(res, 200, { fileId, filename: f.filename, storedName, type: f.type, detectedMime: magic.detectedMime, magicTrusted: magic.trusted, size: f.content.length, capabilities: capabilitiesForFile({ type: f.type, detectedMime: magic.detectedMime }) }); }
    if (req.method === 'POST' && (url.pathname === '/api/command' || url.pathname === '/api/run')) { const p = JSON.parse((await body(req)).toString() || '{}'); const fileId = path.basename(p.fileId || ''), storedName = path.basename(p.storedName || ''); const inputPath = resolveTemp(fileId, storedName); const st = await fs.stat(inputPath).catch(() => null); if (!st) return json(res, 400, { error: 'Uploaded file was not found or expired.' }); const outputName = `out-${randomId()}-${storedName}`, outputPath = resolveTemp(fileId, outputName); const built = buildExifArgs({ ...p, inputPath, outputPath }); if (url.pathname === '/api/command') return json(res, 200, built); const result = await runExiftool(built.args); const exists = await fs.stat(outputPath).then(s => s.isFile()).catch(() => false); let explorer = null; if (!built.modifies) { const explorerCommand = buildExplorerArgs(inputPath); try { const explorerResult = await runExiftool(explorerCommand.args); explorer = { ...parseExplorerJson(explorerResult.stdout), command: explorerCommand.command, args: explorerCommand.args, explanations: explorerCommand.explanations, error: explorerResult.code === 0 ? null : explorerResult.stderr }; } catch (error) { explorer = { rows: [], groups: {}, stats: { totalTags: 0, totalGroups: 0, duplicateTagCount: 0, gpsGroups: 0, dateTimeGroups: 0, embeddedImageGroups: 0 }, findings: [], command: explorerCommand.command, args: explorerCommand.args, explanations: explorerCommand.explanations, error: publicError(error) }; } } return json(res, 200, { ...built, ...result, download: exists ? `/api/download/${fileId}/${outputName}` : null, organized: organize(result.stdout), explorer }); }


    if (req.method === 'POST' && url.pathname === '/api/tool') { const p = JSON.parse((await body(req)).toString() || '{}'); const fileId = path.basename(p.fileId || ''), storedName = path.basename(p.storedName || ''); const inputPath = resolveTemp(fileId, storedName); const st = await fs.stat(inputPath).catch(() => null); if (!st) return json(res, 400, { error: 'Uploaded file was not found or expired.' }); const availability = await getToolAvailability(); const unavailable = (id) => !availability[id]?.installed ? `${toolRegistry[id].displayName} is unavailable. Install with: ${toolRegistry[id].installHint}` : null; const run = async (id, args) => { const miss = unavailable(id); if (miss) throw new Error(miss); return safeRunTool(id, [...args, inputPath], { cwd: resolveTemp(fileId) }); }; const kind = p.analysis; if (kind === 'media') { const out = { mediaInfo: null, ffprobe: null, exiftool: null, commands: [], failures: [] }; try { const r = await run('mediainfo', ['--Output=JSON']); out.mediaInfo = { summary: parseMediaInfoJson(r.stdout), raw: r.stdout }; out.commands.push(buildCommand('mediainfo', ['--Output=JSON'])); } catch (e) { out.failures.push({ tool: 'mediainfo', error: publicError(e) }); } try { const r = await run('ffprobe', ['-v','error','-print_format','json','-show_format','-show_streams']); out.ffprobe = { summary: parseFfprobeJson(r.stdout), raw: r.stdout }; out.commands.push(buildCommand('ffprobe', ['-v','error','-print_format','json','-show_format','-show_streams'])); } catch (e) { out.failures.push({ tool: 'ffprobe', error: publicError(e) }); } return json(res, 200, out); }
      if (kind === 'image') { try { const r = await run('identify', ['-verbose']); return json(res, 200, { summary: parseIdentify(r.stdout), raw: r.stdout, command: buildCommand('identify', ['-verbose']) }); } catch (e) { return json(res, 400, { error: publicError(e) }); } }
      if (kind === 'strings') { try { const min = Number(p.minLength || 6); const r = await run('strings', ['-n', String(min)]); const rows = extractPrintableStrings(Buffer.from(r.stdout), min); return json(res, 200, { rows, raw: r.stdout, truncated: r.stdout.length >= toolRegistry.strings.maxOutputBytes || rows.length >= outputLimits.stringsMaxCount, command: buildCommand('strings', ['-n', String(min)]) }); } catch (e) { return json(res, 400, { error: publicError(e) }); } }
      if (kind === 'qr') { try { const r = await run('zbarimg', ['--quiet']); return json(res, 200, { codes: parseQrOutput(r.stdout), raw: r.stdout, command: buildCommand('zbarimg', ['--quiet']) }); } catch (e) { return json(res, 200, { codes: [], raw: '', warning: publicError(e), command: buildCommand('zbarimg', ['--quiet']) }); } }
      if (kind === 'ocr') { try { const lang = validateOcrLanguage(p.language || 'eng'); const miss = unavailable('tesseract'); if (miss) throw new Error(miss); const r = await safeRunTool('tesseract', [inputPath, 'stdout','-l', lang], { cwd: resolveTemp(fileId) }); const text = r.stdout.trim(); return json(res, 200, { text, message: text ? null : 'No readable text detected.', command: buildCommand('tesseract', ['stdout','-l']) }); } catch (e) { return json(res, 400, { error: publicError(e) }); } }
      if (kind === 'binary') { try { const r = await run('binwalk', []); return json(res, 200, { signatures: parseBinwalk(r.stdout), raw: r.stdout, warning: 'Signatures may be false positives. Extraction is disabled.', command: buildCommand('binwalk', []) }); } catch (e) { return json(res, 400, { error: publicError(e) }); } }
      if (kind === 'embedded') { const resources = ['ThumbnailImage','PreviewImage','JpgFromRaw','CoverArt'].map((tag) => ({ tag, group: 'ExifTool', size: 'Unknown', likelyType: tag.includes('Image') || tag.includes('Jpg') ? 'image/jpeg' : 'Unknown', extractable: true })); return json(res, 200, { resources, command: buildCommand('exiftool', ['-b','-thumbnailimage']) }); }
      if (kind === 'frame') { try { const miss = unavailable('ffmpeg'); if (miss) throw new Error(miss); const ts = p.mode === 'first' ? 0 : assertTimestampWithinDuration(p.timestamp || '0', Number(p.duration || Infinity)); const output = frameOutputPath(fileId, 'frame.jpg'); const r = await safeRunTool('ffmpeg', ['-y','-ss', String(ts), '-i', inputPath, '-frames:v', '1', output], { cwd: resolveTemp(fileId) }); const size = await fs.stat(output).then(x=>x.size).catch(()=>0); if (size > outputLimits.maxExtractedBytes) throw new Error('Extracted frame exceeds size limit.'); return json(res, 200, { download: `/api/download/${fileId}/${path.basename(output)}`, command: r.command }); } catch (e) { return json(res, 400, { error: publicError(e) }); } }
      return json(res, 400, { error: 'Unknown analysis.' }); }
    if (req.method === 'POST' && url.pathname === '/api/report-download') { const p = JSON.parse((await body(req)).toString() || '{}'); const format = p.format === 'text' ? 'text' : 'json'; const text = format === 'text' ? reportText(p.report || {}) : JSON.stringify(p.report || {}, null, 2); res.writeHead(200, { 'content-type': format === 'text' ? 'text/plain' : 'application/json', 'content-disposition': `attachment; filename="metadata-lab-report.${format === 'text' ? 'txt' : 'json'}"` }); return res.end(text.slice(0, 512000)); }
    if (req.method === 'POST' && url.pathname === '/api/investigate') { const p = JSON.parse((await body(req)).toString() || '{}'); const fileId = path.basename(p.fileId || ''), storedName = path.basename(p.storedName || ''); const inputPath = resolveTemp(fileId, storedName); const st = await fs.stat(inputPath).catch(() => null); if (!st) return json(res, 400, { error: 'Uploaded file was not found or expired.' }); const file = { ...p, fileId, storedName, size: st.size }; const availability = await getToolAvailability(); const requested = Array.isArray(p.analyses) ? p.analyses : ['hashes', 'strings']; const completed = [], failed = [], commands = []; const result = { capabilities: capabilitiesForFile(file, availability), availability }; if (requested.includes('hashes')) { try { result.hashes = await hashFile(inputPath); completed.push('hashes'); } catch (e) { failed.push({ id: 'hashes', error: publicError(e) }); } } if (requested.includes('strings')) { try { const min = Number(p.minLength || 6); result.strings = extractPrintableStrings(await fs.readFile(inputPath), min); commands.push(`strings -n ${min} ${path.basename(storedName)}`); completed.push('strings'); } catch (e) { failed.push({ id: 'strings', error: publicError(e) }); } } result.report = await buildInvestigationReport({ file, hashes: result.hashes, completed, failed, availability, commands }); result.completed = completed; result.failed = failed; return json(res, 200, result); }
    if (req.method === 'POST' && url.pathname === '/api/verify-hash') { const p = JSON.parse((await body(req)).toString() || '{}'); return json(res, 200, verifyHash(p.actual, p.expected)); }
    if (req.method === 'POST' && url.pathname === '/api/validate-ocr-language') { const p = JSON.parse((await body(req)).toString() || '{}'); return json(res, 200, { language: validateOcrLanguage(p.language || 'eng') }); }
    if (req.method === 'POST' && url.pathname === '/api/validate-timestamp') { const p = JSON.parse((await body(req)).toString() || '{}'); return json(res, 200, { timestamp: validateTimestamp(p.timestamp) }); }
    if (req.method === 'POST' && url.pathname === '/api/panic') { await fs.rm(config.tempRoot, { recursive: true, force: true }); await ensureTempRoot(); return json(res, 200, { ok: true }); }
    if (req.method === 'GET' && url.pathname.startsWith('/api/download/')) { const [, , , fid, ...nm] = url.pathname.split('/'); const filename = path.basename(nm.join('/')); const p = resolveTemp(path.basename(fid), filename); const st = await fs.stat(p).catch(() => null); if (!st?.isFile()) return json(res, 404, { error: 'Download file was not found or expired.' }); res.writeHead(200, { 'content-disposition': 'attachment; filename="' + filename.replaceAll('"', '') + '"' }); return fss.createReadStream(p).pipe(res); }
    const file = url.pathname === '/' ? '/index.html' : url.pathname; const p = path.resolve('public', file.slice(1)); if (!p.startsWith(path.resolve('public'))) return json(res, 404, { error: 'Not found.' }); const data = await fs.readFile(p).catch(() => null); if (!data) return json(res, 404, { error: 'Not found.' }); res.writeHead(200, { 'content-type': mime(p) }); res.end(data);
  } catch (e) { json(res, 400, { error: publicError(e) }); }
}
function organize(stdout) { const groups = {}; for (const line of stdout.split('\n')) { const m = line.match(/^\[([^\]]+)\]\s*([^:]+):\s*(.*)$/) || line.match(/^([^:]+):\s*(.*)$/); if (m) { const g = m.length === 4 ? m[1] : 'General', k = m.length === 4 ? m[2] : m[1], v = m.length === 4 ? m[3] : m[2]; (groups[g] ||= []).push({ key: k.trim(), value: v.trim() }); } } return groups; }
function mime(p) { return p.endsWith('.css') ? 'text/css' : p.endsWith('.js') ? 'text/javascript' : p.endsWith('.webmanifest') ? 'application/manifest+json' : 'text/html'; }
export function createServer() { return http.createServer(handler); }
